/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AuthenticationV1TokenReviewSpec : TokenReviewSpec is a description of the token authentication request.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AuthenticationV1TokenReviewSpec {
  /// Token is the opaque bearer token.
  #[serde(rename = "token")]
  token: Option<String>
}

impl AuthenticationV1TokenReviewSpec {
  /// TokenReviewSpec is a description of the token authentication request.
  pub fn new() -> AuthenticationV1TokenReviewSpec {
    AuthenticationV1TokenReviewSpec {
      token: None
    }
  }

  pub fn set_token(&mut self, token: String) {
    self.token = Some(token);
  }

  pub fn with_token(mut self, token: String) -> AuthenticationV1TokenReviewSpec {
    self.token = Some(token);
    self
  }

  pub fn token(&self) -> Option<&String> {
    self.token.as_ref()
  }

  pub fn reset_token(&mut self) {
    self.token = None;
  }

}



