/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AppsV1beta1RollbackConfig {
  /// The revision to rollback to. If set to 0, rollback to the last revision.
  #[serde(rename = "revision")]
  revision: Option<i64>
}

impl AppsV1beta1RollbackConfig {
  pub fn new() -> AppsV1beta1RollbackConfig {
    AppsV1beta1RollbackConfig {
      revision: None
    }
  }

  pub fn set_revision(&mut self, revision: i64) {
    self.revision = Some(revision);
  }

  pub fn with_revision(mut self, revision: i64) -> AppsV1beta1RollbackConfig {
    self.revision = Some(revision);
    self
  }

  pub fn revision(&self) -> Option<&i64> {
    self.revision.as_ref()
  }

  pub fn reset_revision(&mut self) {
    self.revision = None;
  }

}



