/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AppsV1beta1RollingUpdateStatefulSetStrategy : RollingUpdateStatefulSetStrategy is used to communicate parameter for RollingUpdateStatefulSetStrategyType.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AppsV1beta1RollingUpdateStatefulSetStrategy {
  /// Partition indicates the ordinal at which the StatefulSet should be partitioned.
  #[serde(rename = "partition")]
  partition: Option<i32>
}

impl AppsV1beta1RollingUpdateStatefulSetStrategy {
  /// RollingUpdateStatefulSetStrategy is used to communicate parameter for RollingUpdateStatefulSetStrategyType.
  pub fn new() -> AppsV1beta1RollingUpdateStatefulSetStrategy {
    AppsV1beta1RollingUpdateStatefulSetStrategy {
      partition: None
    }
  }

  pub fn set_partition(&mut self, partition: i32) {
    self.partition = Some(partition);
  }

  pub fn with_partition(mut self, partition: i32) -> AppsV1beta1RollingUpdateStatefulSetStrategy {
    self.partition = Some(partition);
    self
  }

  pub fn partition(&self) -> Option<&i32> {
    self.partition.as_ref()
  }

  pub fn reset_partition(&mut self) {
    self.partition = None;
  }

}



