/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ExtensionsV1beta1HostPortRange : Host Port Range defines a range of host ports that will be enabled by a policy for pods to use.  It requires both the start and end to be defined.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ExtensionsV1beta1HostPortRange {
  /// max is the end of the range, inclusive.
  #[serde(rename = "max")]
  max: i32,
  /// min is the start of the range, inclusive.
  #[serde(rename = "min")]
  min: i32
}

impl ExtensionsV1beta1HostPortRange {
  /// Host Port Range defines a range of host ports that will be enabled by a policy for pods to use.  It requires both the start and end to be defined.
  pub fn new(max: i32, min: i32) -> ExtensionsV1beta1HostPortRange {
    ExtensionsV1beta1HostPortRange {
      max: max,
      min: min
    }
  }

  pub fn set_max(&mut self, max: i32) {
    self.max = max;
  }

  pub fn with_max(mut self, max: i32) -> ExtensionsV1beta1HostPortRange {
    self.max = max;
    self
  }

  pub fn max(&self) -> &i32 {
    &self.max
  }


  pub fn set_min(&mut self, min: i32) {
    self.min = min;
  }

  pub fn with_min(mut self, min: i32) -> ExtensionsV1beta1HostPortRange {
    self.min = min;
    self
  }

  pub fn min(&self) -> &i32 {
    &self.min
  }


}



