/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration : ExternalAdmissionHookConfiguration describes the configuration of initializers.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration {
  /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
  #[serde(rename = "apiVersion")]
  api_version: Option<String>,
  /// ExternalAdmissionHooks is a list of external admission webhooks and the affected resources and operations.
  #[serde(rename = "externalAdmissionHooks")]
  external_admission_hooks: Option<Vec<::models::AdmissionregistrationV1alpha1ExternalAdmissionHook>>,
  /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
  #[serde(rename = "kind")]
  kind: Option<String>,
  /// Standard object metadata; More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata.
  #[serde(rename = "metadata")]
  metadata: Option<::models::MetaV1ObjectMeta>
}

impl AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration {
  /// ExternalAdmissionHookConfiguration describes the configuration of initializers.
  pub fn new() -> AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration {
    AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration {
      api_version: None,
      external_admission_hooks: None,
      kind: None,
      metadata: None
    }
  }

  pub fn set_api_version(&mut self, api_version: String) {
    self.api_version = Some(api_version);
  }

  pub fn with_api_version(mut self, api_version: String) -> AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration {
    self.api_version = Some(api_version);
    self
  }

  pub fn api_version(&self) -> Option<&String> {
    self.api_version.as_ref()
  }

  pub fn reset_api_version(&mut self) {
    self.api_version = None;
  }

  pub fn set_external_admission_hooks(&mut self, external_admission_hooks: Vec<::models::AdmissionregistrationV1alpha1ExternalAdmissionHook>) {
    self.external_admission_hooks = Some(external_admission_hooks);
  }

  pub fn with_external_admission_hooks(mut self, external_admission_hooks: Vec<::models::AdmissionregistrationV1alpha1ExternalAdmissionHook>) -> AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration {
    self.external_admission_hooks = Some(external_admission_hooks);
    self
  }

  pub fn external_admission_hooks(&self) -> Option<&Vec<::models::AdmissionregistrationV1alpha1ExternalAdmissionHook>> {
    self.external_admission_hooks.as_ref()
  }

  pub fn reset_external_admission_hooks(&mut self) {
    self.external_admission_hooks = None;
  }

  pub fn set_kind(&mut self, kind: String) {
    self.kind = Some(kind);
  }

  pub fn with_kind(mut self, kind: String) -> AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration {
    self.kind = Some(kind);
    self
  }

  pub fn kind(&self) -> Option<&String> {
    self.kind.as_ref()
  }

  pub fn reset_kind(&mut self) {
    self.kind = None;
  }

  pub fn set_metadata(&mut self, metadata: ::models::MetaV1ObjectMeta) {
    self.metadata = Some(metadata);
  }

  pub fn with_metadata(mut self, metadata: ::models::MetaV1ObjectMeta) -> AdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration {
    self.metadata = Some(metadata);
    self
  }

  pub fn metadata(&self) -> Option<&::models::MetaV1ObjectMeta> {
    self.metadata.as_ref()
  }

  pub fn reset_metadata(&mut self) {
    self.metadata = None;
  }

}



