/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1AttachedVolume : AttachedVolume describes a volume attached to a node

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct V1AttachedVolume {
  /// DevicePath represents the device path where the volume should be available
  #[serde(rename = "devicePath")]
  device_path: String,
  /// Name of the attached volume
  #[serde(rename = "name")]
  name: String
}

impl V1AttachedVolume {
  /// AttachedVolume describes a volume attached to a node
  pub fn new(device_path: String, name: String) -> V1AttachedVolume {
    V1AttachedVolume {
      device_path: device_path,
      name: name
    }
  }

  pub fn set_device_path(&mut self, device_path: String) {
    self.device_path = device_path;
  }

  pub fn with_device_path(mut self, device_path: String) -> V1AttachedVolume {
    self.device_path = device_path;
    self
  }

  pub fn device_path(&self) -> &String {
    &self.device_path
  }


  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> V1AttachedVolume {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


}



