/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1ContainerStateWaiting : ContainerStateWaiting is a waiting state of a container.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct V1ContainerStateWaiting {
  /// Message regarding why the container is not yet running.
  #[serde(rename = "message")]
  message: Option<String>,
  /// (brief) reason the container is not yet running.
  #[serde(rename = "reason")]
  reason: Option<String>
}

impl V1ContainerStateWaiting {
  /// ContainerStateWaiting is a waiting state of a container.
  pub fn new() -> V1ContainerStateWaiting {
    V1ContainerStateWaiting {
      message: None,
      reason: None
    }
  }

  pub fn set_message(&mut self, message: String) {
    self.message = Some(message);
  }

  pub fn with_message(mut self, message: String) -> V1ContainerStateWaiting {
    self.message = Some(message);
    self
  }

  pub fn message(&self) -> Option<&String> {
    self.message.as_ref()
  }

  pub fn reset_message(&mut self) {
    self.message = None;
  }

  pub fn set_reason(&mut self, reason: String) {
    self.reason = Some(reason);
  }

  pub fn with_reason(mut self, reason: String) -> V1ContainerStateWaiting {
    self.reason = Some(reason);
    self
  }

  pub fn reason(&self) -> Option<&String> {
    self.reason.as_ref()
  }

  pub fn reset_reason(&mut self) {
    self.reason = None;
  }

}



