/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1NodeSelectorTerm : A null or empty node selector term matches no objects.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct V1NodeSelectorTerm {
  /// Required. A list of node selector requirements. The requirements are ANDed.
  #[serde(rename = "matchExpressions")]
  match_expressions: Vec<::models::V1NodeSelectorRequirement>
}

impl V1NodeSelectorTerm {
  /// A null or empty node selector term matches no objects.
  pub fn new(match_expressions: Vec<::models::V1NodeSelectorRequirement>) -> V1NodeSelectorTerm {
    V1NodeSelectorTerm {
      match_expressions: match_expressions
    }
  }

  pub fn set_match_expressions(&mut self, match_expressions: Vec<::models::V1NodeSelectorRequirement>) {
    self.match_expressions = match_expressions;
  }

  pub fn with_match_expressions(mut self, match_expressions: Vec<::models::V1NodeSelectorRequirement>) -> V1NodeSelectorTerm {
    self.match_expressions = match_expressions;
    self
  }

  pub fn match_expressions(&self) -> &Vec<::models::V1NodeSelectorRequirement> {
    &self.match_expressions
  }


}



