/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NetworkingV1NetworkPolicyIngressRule : NetworkPolicyIngressRule describes a particular set of traffic that is allowed to the pods matched by a NetworkPolicySpec's podSelector. The traffic must match both ports and from.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct NetworkingV1NetworkPolicyIngressRule {
  /// List of sources which should be able to access the pods selected for this rule. Items in this list are combined using a logical OR operation. If this field is empty or missing, this rule matches all sources (traffic not restricted by source). If this field is present and contains at least on item, this rule allows traffic only if the traffic matches at least one item in the from list.
  #[serde(rename = "from")]
  from: Option<Vec<::models::NetworkingV1NetworkPolicyPeer>>,
  /// List of ports which should be made accessible on the pods selected for this rule. Each item in this list is combined using a logical OR. If this field is empty or missing, this rule matches all ports (traffic not restricted by port). If this field is present and contains at least one item, then this rule allows traffic only if the traffic matches at least one port in the list.
  #[serde(rename = "ports")]
  ports: Option<Vec<::models::NetworkingV1NetworkPolicyPort>>
}

impl NetworkingV1NetworkPolicyIngressRule {
  /// NetworkPolicyIngressRule describes a particular set of traffic that is allowed to the pods matched by a NetworkPolicySpec's podSelector. The traffic must match both ports and from.
  pub fn new() -> NetworkingV1NetworkPolicyIngressRule {
    NetworkingV1NetworkPolicyIngressRule {
      from: None,
      ports: None
    }
  }

  pub fn set_from(&mut self, from: Vec<::models::NetworkingV1NetworkPolicyPeer>) {
    self.from = Some(from);
  }

  pub fn with_from(mut self, from: Vec<::models::NetworkingV1NetworkPolicyPeer>) -> NetworkingV1NetworkPolicyIngressRule {
    self.from = Some(from);
    self
  }

  pub fn from(&self) -> Option<&Vec<::models::NetworkingV1NetworkPolicyPeer>> {
    self.from.as_ref()
  }

  pub fn reset_from(&mut self) {
    self.from = None;
  }

  pub fn set_ports(&mut self, ports: Vec<::models::NetworkingV1NetworkPolicyPort>) {
    self.ports = Some(ports);
  }

  pub fn with_ports(mut self, ports: Vec<::models::NetworkingV1NetworkPolicyPort>) -> NetworkingV1NetworkPolicyIngressRule {
    self.ports = Some(ports);
    self
  }

  pub fn ports(&self) -> Option<&Vec<::models::NetworkingV1NetworkPolicyPort>> {
    self.ports.as_ref()
  }

  pub fn reset_ports(&mut self) {
    self.ports = None;
  }

}



