/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AutoscalingV2alpha1ResourceMetricSource : ResourceMetricSource indicates how to scale on a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  The values will be averaged together before being compared to the target.  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.  Only one \"target\" type should be set.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AutoscalingV2alpha1ResourceMetricSource {
  /// name is the name of the resource in question.
  #[serde(rename = "name")]
  name: String,
  /// targetAverageUtilization is the target value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.
  #[serde(rename = "targetAverageUtilization")]
  target_average_utilization: Option<i32>,
  /// targetAverageValue is the target value of the average of the resource metric across all relevant pods, as a raw value (instead of as a percentage of the request), similar to the \"pods\" metric source type.
  #[serde(rename = "targetAverageValue")]
  target_average_value: Option<::models::ResourceQuantity>
}

impl AutoscalingV2alpha1ResourceMetricSource {
  /// ResourceMetricSource indicates how to scale on a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  The values will be averaged together before being compared to the target.  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.  Only one \"target\" type should be set.
  pub fn new(name: String) -> AutoscalingV2alpha1ResourceMetricSource {
    AutoscalingV2alpha1ResourceMetricSource {
      name: name,
      target_average_utilization: None,
      target_average_value: None
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> AutoscalingV2alpha1ResourceMetricSource {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


  pub fn set_target_average_utilization(&mut self, target_average_utilization: i32) {
    self.target_average_utilization = Some(target_average_utilization);
  }

  pub fn with_target_average_utilization(mut self, target_average_utilization: i32) -> AutoscalingV2alpha1ResourceMetricSource {
    self.target_average_utilization = Some(target_average_utilization);
    self
  }

  pub fn target_average_utilization(&self) -> Option<&i32> {
    self.target_average_utilization.as_ref()
  }

  pub fn reset_target_average_utilization(&mut self) {
    self.target_average_utilization = None;
  }

  pub fn set_target_average_value(&mut self, target_average_value: ::models::ResourceQuantity) {
    self.target_average_value = Some(target_average_value);
  }

  pub fn with_target_average_value(mut self, target_average_value: ::models::ResourceQuantity) -> AutoscalingV2alpha1ResourceMetricSource {
    self.target_average_value = Some(target_average_value);
    self
  }

  pub fn target_average_value(&self) -> Option<&::models::ResourceQuantity> {
    self.target_average_value.as_ref()
  }

  pub fn reset_target_average_value(&mut self) {
    self.target_average_value = None;
  }

}



