/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MetaV1Patch : Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MetaV1Patch {
}

impl MetaV1Patch {
  /// Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.
  pub fn new() -> MetaV1Patch {
    MetaV1Patch {
    }
  }

}



