/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1NodeSelector : A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct V1NodeSelector {
  /// Required. A list of node selector terms. The terms are ORed.
  #[serde(rename = "nodeSelectorTerms")]
  node_selector_terms: Vec<::models::V1NodeSelectorTerm>
}

impl V1NodeSelector {
  /// A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
  pub fn new(node_selector_terms: Vec<::models::V1NodeSelectorTerm>) -> V1NodeSelector {
    V1NodeSelector {
      node_selector_terms: node_selector_terms
    }
  }

  pub fn set_node_selector_terms(&mut self, node_selector_terms: Vec<::models::V1NodeSelectorTerm>) {
    self.node_selector_terms = node_selector_terms;
  }

  pub fn with_node_selector_terms(mut self, node_selector_terms: Vec<::models::V1NodeSelectorTerm>) -> V1NodeSelector {
    self.node_selector_terms = node_selector_terms;
    self
  }

  pub fn node_selector_terms(&self) -> &Vec<::models::V1NodeSelectorTerm> {
    &self.node_selector_terms
  }


}



