/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1DaemonEndpoint : DaemonEndpoint contains information about a single Daemon endpoint.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1DaemonEndpoint {
  /// Port number of the given endpoint.
  #[serde(rename = "Port")]
  port: i32
}

impl V1DaemonEndpoint {
  /// DaemonEndpoint contains information about a single Daemon endpoint.
  pub fn new(port: i32) -> V1DaemonEndpoint {
    V1DaemonEndpoint {
      port: port
    }
  }

  pub fn set_port(&mut self, port: i32) {
    self.port = port;
  }

  pub fn with_port(mut self, port: i32) -> V1DaemonEndpoint {
    self.port = port;
    self
  }

  pub fn port(&self) -> &i32 {
    &self.port
  }


}



