/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AutoscalingV2alpha1ObjectMetricStatus : ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AutoscalingV2alpha1ObjectMetricStatus {
  /// currentValue is the current value of the metric (as a quantity).
  #[serde(rename = "currentValue")]
  current_value: ::models::ResourceQuantity,
  /// metricName is the name of the metric in question.
  #[serde(rename = "metricName")]
  metric_name: String,
  /// target is the described Kubernetes object.
  #[serde(rename = "target")]
  target: ::models::AutoscalingV2alpha1CrossVersionObjectReference
}

impl AutoscalingV2alpha1ObjectMetricStatus {
  /// ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
  pub fn new(current_value: ::models::ResourceQuantity, metric_name: String, target: ::models::AutoscalingV2alpha1CrossVersionObjectReference) -> AutoscalingV2alpha1ObjectMetricStatus {
    AutoscalingV2alpha1ObjectMetricStatus {
      current_value: current_value,
      metric_name: metric_name,
      target: target
    }
  }

  pub fn set_current_value(&mut self, current_value: ::models::ResourceQuantity) {
    self.current_value = current_value;
  }

  pub fn with_current_value(mut self, current_value: ::models::ResourceQuantity) -> AutoscalingV2alpha1ObjectMetricStatus {
    self.current_value = current_value;
    self
  }

  pub fn current_value(&self) -> &::models::ResourceQuantity {
    &self.current_value
  }


  pub fn set_metric_name(&mut self, metric_name: String) {
    self.metric_name = metric_name;
  }

  pub fn with_metric_name(mut self, metric_name: String) -> AutoscalingV2alpha1ObjectMetricStatus {
    self.metric_name = metric_name;
    self
  }

  pub fn metric_name(&self) -> &String {
    &self.metric_name
  }


  pub fn set_target(&mut self, target: ::models::AutoscalingV2alpha1CrossVersionObjectReference) {
    self.target = target;
  }

  pub fn with_target(mut self, target: ::models::AutoscalingV2alpha1CrossVersionObjectReference) -> AutoscalingV2alpha1ObjectMetricStatus {
    self.target = target;
    self
  }

  pub fn target(&self) -> &::models::AutoscalingV2alpha1CrossVersionObjectReference {
    &self.target
  }


}



