/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1Capabilities : Adds and removes POSIX capabilities from running containers.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct V1Capabilities {
  /// Added capabilities
  #[serde(rename = "add")]
  add: Option<Vec<String>>,
  /// Removed capabilities
  #[serde(rename = "drop")]
  drop: Option<Vec<String>>
}

impl V1Capabilities {
  /// Adds and removes POSIX capabilities from running containers.
  pub fn new() -> V1Capabilities {
    V1Capabilities {
      add: None,
      drop: None
    }
  }

  pub fn set_add(&mut self, add: Vec<String>) {
    self.add = Some(add);
  }

  pub fn with_add(mut self, add: Vec<String>) -> V1Capabilities {
    self.add = Some(add);
    self
  }

  pub fn add(&self) -> Option<&Vec<String>> {
    self.add.as_ref()
  }

  pub fn reset_add(&mut self) {
    self.add = None;
  }

  pub fn set_drop(&mut self, drop: Vec<String>) {
    self.drop = Some(drop);
  }

  pub fn with_drop(mut self, drop: Vec<String>) -> V1Capabilities {
    self.drop = Some(drop);
    self
  }

  pub fn drop(&self) -> Option<&Vec<String>> {
    self.drop.as_ref()
  }

  pub fn reset_drop(&mut self) {
    self.drop = None;
  }

}



