/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1Affinity : Affinity is a group of affinity scheduling rules.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct V1Affinity {
  /// Describes node affinity scheduling rules for the pod.
  #[serde(rename = "nodeAffinity")]
  node_affinity: Option<::models::V1NodeAffinity>,
  /// Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s)).
  #[serde(rename = "podAffinity")]
  pod_affinity: Option<::models::V1PodAffinity>,
  /// Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s)).
  #[serde(rename = "podAntiAffinity")]
  pod_anti_affinity: Option<::models::V1PodAntiAffinity>
}

impl V1Affinity {
  /// Affinity is a group of affinity scheduling rules.
  pub fn new() -> V1Affinity {
    V1Affinity {
      node_affinity: None,
      pod_affinity: None,
      pod_anti_affinity: None
    }
  }

  pub fn set_node_affinity(&mut self, node_affinity: ::models::V1NodeAffinity) {
    self.node_affinity = Some(node_affinity);
  }

  pub fn with_node_affinity(mut self, node_affinity: ::models::V1NodeAffinity) -> V1Affinity {
    self.node_affinity = Some(node_affinity);
    self
  }

  pub fn node_affinity(&self) -> Option<&::models::V1NodeAffinity> {
    self.node_affinity.as_ref()
  }

  pub fn reset_node_affinity(&mut self) {
    self.node_affinity = None;
  }

  pub fn set_pod_affinity(&mut self, pod_affinity: ::models::V1PodAffinity) {
    self.pod_affinity = Some(pod_affinity);
  }

  pub fn with_pod_affinity(mut self, pod_affinity: ::models::V1PodAffinity) -> V1Affinity {
    self.pod_affinity = Some(pod_affinity);
    self
  }

  pub fn pod_affinity(&self) -> Option<&::models::V1PodAffinity> {
    self.pod_affinity.as_ref()
  }

  pub fn reset_pod_affinity(&mut self) {
    self.pod_affinity = None;
  }

  pub fn set_pod_anti_affinity(&mut self, pod_anti_affinity: ::models::V1PodAntiAffinity) {
    self.pod_anti_affinity = Some(pod_anti_affinity);
  }

  pub fn with_pod_anti_affinity(mut self, pod_anti_affinity: ::models::V1PodAntiAffinity) -> V1Affinity {
    self.pod_anti_affinity = Some(pod_anti_affinity);
    self
  }

  pub fn pod_anti_affinity(&self) -> Option<&::models::V1PodAntiAffinity> {
    self.pod_anti_affinity.as_ref()
  }

  pub fn reset_pod_anti_affinity(&mut self) {
    self.pod_anti_affinity = None;
  }

}



