/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1ObjectFieldSelector : ObjectFieldSelector selects an APIVersioned field of an object.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1ObjectFieldSelector {
  /// Version of the schema the FieldPath is written in terms of, defaults to \"v1\".
  #[serde(rename = "apiVersion")]
  api_version: Option<String>,
  /// Path of the field to select in the specified API version.
  #[serde(rename = "fieldPath")]
  field_path: String
}

impl V1ObjectFieldSelector {
  /// ObjectFieldSelector selects an APIVersioned field of an object.
  pub fn new(field_path: String) -> V1ObjectFieldSelector {
    V1ObjectFieldSelector {
      api_version: None,
      field_path: field_path
    }
  }

  pub fn set_api_version(&mut self, api_version: String) {
    self.api_version = Some(api_version);
  }

  pub fn with_api_version(mut self, api_version: String) -> V1ObjectFieldSelector {
    self.api_version = Some(api_version);
    self
  }

  pub fn api_version(&self) -> Option<&String> {
    self.api_version.as_ref()
  }

  pub fn reset_api_version(&mut self) {
    self.api_version = None;
  }

  pub fn set_field_path(&mut self, field_path: String) {
    self.field_path = field_path;
  }

  pub fn with_field_path(mut self, field_path: String) -> V1ObjectFieldSelector {
    self.field_path = field_path;
    self
  }

  pub fn field_path(&self) -> &String {
    &self.field_path
  }


}



