/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1ContainerImage : Describe a container image

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct V1ContainerImage {
  /// Names by which this image is known. e.g. [\"gcr.io/google_containers/hyperkube:v1.0.7\", \"dockerhub.io/google_containers/hyperkube:v1.0.7\"]
  #[serde(rename = "names")]
  names: Vec<String>,
  /// The size of the image in bytes.
  #[serde(rename = "sizeBytes")]
  size_bytes: Option<i64>
}

impl V1ContainerImage {
  /// Describe a container image
  pub fn new(names: Vec<String>) -> V1ContainerImage {
    V1ContainerImage {
      names: names,
      size_bytes: None
    }
  }

  pub fn set_names(&mut self, names: Vec<String>) {
    self.names = names;
  }

  pub fn with_names(mut self, names: Vec<String>) -> V1ContainerImage {
    self.names = names;
    self
  }

  pub fn names(&self) -> &Vec<String> {
    &self.names
  }


  pub fn set_size_bytes(&mut self, size_bytes: i64) {
    self.size_bytes = Some(size_bytes);
  }

  pub fn with_size_bytes(mut self, size_bytes: i64) -> V1ContainerImage {
    self.size_bytes = Some(size_bytes);
    self
  }

  pub fn size_bytes(&self) -> Option<&i64> {
    self.size_bytes.as_ref()
  }

  pub fn reset_size_bytes(&mut self) {
    self.size_bytes = None;
  }

}



