/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1LocalVolumeSource : Local represents directly-attached storage with node affinity

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct V1LocalVolumeSource {
  /// The full path to the volume on the node For alpha, this path must be a directory Once block as a source is supported, then this path can point to a block device
  #[serde(rename = "path")]
  path: String
}

impl V1LocalVolumeSource {
  /// Local represents directly-attached storage with node affinity
  pub fn new(path: String) -> V1LocalVolumeSource {
    V1LocalVolumeSource {
      path: path
    }
  }

  pub fn set_path(&mut self, path: String) {
    self.path = path;
  }

  pub fn with_path(mut self, path: String) -> V1LocalVolumeSource {
    self.path = path;
    self
  }

  pub fn path(&self) -> &String {
    &self.path
  }


}



