/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ExtensionsV1beta1SeLinuxStrategyOptions : SELinux  Strategy Options defines the strategy type and any options used to create the strategy.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ExtensionsV1beta1SeLinuxStrategyOptions {
  /// type is the strategy that will dictate the allowable labels that may be set.
  #[serde(rename = "rule")]
  rule: String,
  /// seLinuxOptions required to run as; required for MustRunAs More info: https://git.k8s.io/community/contributors/design-proposals/security_context.md
  #[serde(rename = "seLinuxOptions")]
  se_linux_options: Option<::models::V1SeLinuxOptions>
}

impl ExtensionsV1beta1SeLinuxStrategyOptions {
  /// SELinux  Strategy Options defines the strategy type and any options used to create the strategy.
  pub fn new(rule: String) -> ExtensionsV1beta1SeLinuxStrategyOptions {
    ExtensionsV1beta1SeLinuxStrategyOptions {
      rule: rule,
      se_linux_options: None
    }
  }

  pub fn set_rule(&mut self, rule: String) {
    self.rule = rule;
  }

  pub fn with_rule(mut self, rule: String) -> ExtensionsV1beta1SeLinuxStrategyOptions {
    self.rule = rule;
    self
  }

  pub fn rule(&self) -> &String {
    &self.rule
  }


  pub fn set_se_linux_options(&mut self, se_linux_options: ::models::V1SeLinuxOptions) {
    self.se_linux_options = Some(se_linux_options);
  }

  pub fn with_se_linux_options(mut self, se_linux_options: ::models::V1SeLinuxOptions) -> ExtensionsV1beta1SeLinuxStrategyOptions {
    self.se_linux_options = Some(se_linux_options);
    self
  }

  pub fn se_linux_options(&self) -> Option<&::models::V1SeLinuxOptions> {
    self.se_linux_options.as_ref()
  }

  pub fn reset_se_linux_options(&mut self) {
    self.se_linux_options = None;
  }

}



