/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// V1EnvVarSource : EnvVarSource represents a source for the value of an EnvVar.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct V1EnvVarSource {
  /// Selects a key of a ConfigMap.
  #[serde(rename = "configMapKeyRef")]
  config_map_key_ref: Option<::models::V1ConfigMapKeySelector>,
  /// Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP.
  #[serde(rename = "fieldRef")]
  field_ref: Option<::models::V1ObjectFieldSelector>,
  /// Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, requests.cpu and requests.memory) are currently supported.
  #[serde(rename = "resourceFieldRef")]
  resource_field_ref: Option<::models::V1ResourceFieldSelector>,
  /// Selects a key of a secret in the pod's namespace
  #[serde(rename = "secretKeyRef")]
  secret_key_ref: Option<::models::V1SecretKeySelector>
}

impl V1EnvVarSource {
  /// EnvVarSource represents a source for the value of an EnvVar.
  pub fn new() -> V1EnvVarSource {
    V1EnvVarSource {
      config_map_key_ref: None,
      field_ref: None,
      resource_field_ref: None,
      secret_key_ref: None
    }
  }

  pub fn set_config_map_key_ref(&mut self, config_map_key_ref: ::models::V1ConfigMapKeySelector) {
    self.config_map_key_ref = Some(config_map_key_ref);
  }

  pub fn with_config_map_key_ref(mut self, config_map_key_ref: ::models::V1ConfigMapKeySelector) -> V1EnvVarSource {
    self.config_map_key_ref = Some(config_map_key_ref);
    self
  }

  pub fn config_map_key_ref(&self) -> Option<&::models::V1ConfigMapKeySelector> {
    self.config_map_key_ref.as_ref()
  }

  pub fn reset_config_map_key_ref(&mut self) {
    self.config_map_key_ref = None;
  }

  pub fn set_field_ref(&mut self, field_ref: ::models::V1ObjectFieldSelector) {
    self.field_ref = Some(field_ref);
  }

  pub fn with_field_ref(mut self, field_ref: ::models::V1ObjectFieldSelector) -> V1EnvVarSource {
    self.field_ref = Some(field_ref);
    self
  }

  pub fn field_ref(&self) -> Option<&::models::V1ObjectFieldSelector> {
    self.field_ref.as_ref()
  }

  pub fn reset_field_ref(&mut self) {
    self.field_ref = None;
  }

  pub fn set_resource_field_ref(&mut self, resource_field_ref: ::models::V1ResourceFieldSelector) {
    self.resource_field_ref = Some(resource_field_ref);
  }

  pub fn with_resource_field_ref(mut self, resource_field_ref: ::models::V1ResourceFieldSelector) -> V1EnvVarSource {
    self.resource_field_ref = Some(resource_field_ref);
    self
  }

  pub fn resource_field_ref(&self) -> Option<&::models::V1ResourceFieldSelector> {
    self.resource_field_ref.as_ref()
  }

  pub fn reset_resource_field_ref(&mut self) {
    self.resource_field_ref = None;
  }

  pub fn set_secret_key_ref(&mut self, secret_key_ref: ::models::V1SecretKeySelector) {
    self.secret_key_ref = Some(secret_key_ref);
  }

  pub fn with_secret_key_ref(mut self, secret_key_ref: ::models::V1SecretKeySelector) -> V1EnvVarSource {
    self.secret_key_ref = Some(secret_key_ref);
    self
  }

  pub fn secret_key_ref(&self) -> Option<&::models::V1SecretKeySelector> {
    self.secret_key_ref.as_ref()
  }

  pub fn reset_secret_key_ref(&mut self) {
    self.secret_key_ref = None;
  }

}



