/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MetaV1Preconditions : Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MetaV1Preconditions {
  /// Specifies the target UID.
  #[serde(rename = "uid")]
  uid: Option<String>
}

impl MetaV1Preconditions {
  /// Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.
  pub fn new() -> MetaV1Preconditions {
    MetaV1Preconditions {
      uid: None
    }
  }

  pub fn set_uid(&mut self, uid: String) {
    self.uid = Some(uid);
  }

  pub fn with_uid(mut self, uid: String) -> MetaV1Preconditions {
    self.uid = Some(uid);
    self
  }

  pub fn uid(&self) -> Option<&String> {
    self.uid.as_ref()
  }

  pub fn reset_uid(&mut self) {
    self.uid = None;
  }

}



