/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AutoscalingV2alpha1PodsMetricStatus : PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AutoscalingV2alpha1PodsMetricStatus {
  /// currentAverageValue is the current value of the average of the metric across all relevant pods (as a quantity)
  #[serde(rename = "currentAverageValue")]
  current_average_value: ::models::ResourceQuantity,
  /// metricName is the name of the metric in question
  #[serde(rename = "metricName")]
  metric_name: String
}

impl AutoscalingV2alpha1PodsMetricStatus {
  /// PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).
  pub fn new(current_average_value: ::models::ResourceQuantity, metric_name: String) -> AutoscalingV2alpha1PodsMetricStatus {
    AutoscalingV2alpha1PodsMetricStatus {
      current_average_value: current_average_value,
      metric_name: metric_name
    }
  }

  pub fn set_current_average_value(&mut self, current_average_value: ::models::ResourceQuantity) {
    self.current_average_value = current_average_value;
  }

  pub fn with_current_average_value(mut self, current_average_value: ::models::ResourceQuantity) -> AutoscalingV2alpha1PodsMetricStatus {
    self.current_average_value = current_average_value;
    self
  }

  pub fn current_average_value(&self) -> &::models::ResourceQuantity {
    &self.current_average_value
  }


  pub fn set_metric_name(&mut self, metric_name: String) {
    self.metric_name = metric_name;
  }

  pub fn with_metric_name(mut self, metric_name: String) -> AutoscalingV2alpha1PodsMetricStatus {
    self.metric_name = metric_name;
    self
  }

  pub fn metric_name(&self) -> &String {
    &self.metric_name
  }


}



